# Generated by Django 4.0.3 on 2022-09-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_codingprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingprofile',
            name='Linkedin',
            field=models.URLField(null=True),
        ),
    ]
